services:
  s1_fetch:
    build: .
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/service/s1_fetch.py ${BATCH_SIZE:-10} ${MAX_PAGES:-3}

  s2_download:
    build: .
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/service/s2_download.py ${BATCH_SIZE:-10} ${HOST:-""}

  s3_subtitle:
    build: .
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/service/s3_subtitle.py ${BATCH_SIZE:-10} ${HOST:-""}

  s4_translate_vtt:
    build: .
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/service/s4_translate_vtt.py ${BATCH_SIZE:-10} ${HOST:-""}

  s5_translate_meta:
    build: .
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/service/s5_translate_meta.py ${BATCH_SIZE:-10} ${HOST:-""}

  s6_upload:
    build: .
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/service/s6_upload.py ${BATCH_SIZE:-10} ${HOST:-""}
