services:
  s1_fetch:
    build: .
    container_name: s1_fetch
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/main.py --runner=s1_fetch

  s2_download:
    build: .
    container_name: s2_download
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/main.py --runner=s2_download

  s3_convert:
    build: .
    container_name: s3_convert
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/main.py --runner=s3_convert

  s4_subtitle:
    build: .
    container_name: s4_subtitle
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/main.py --runner=s4_subtitle --batch_size=1

  s5_translate_vtt:
    build: .
    container_name: s5_translate_vtt
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/main.py --runner=s5_translate_vtt

  s6_translate_meta:
    build: .
    container_name: s6_translate_meta
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/main.py --runner=s6_translate_meta

  s7_upload:
    build: .
    container_name: s7_upload
    env_file:
      - .env
    volumes:
      - ./works:/workspace/works
    command: python src/main.py --runner=s7_upload

#  s8_cleanup:
#    build: .
#    container_name: s8_cleanup
#    env_file:
#      - .env
#    volumes:
#      - ./works:/workspace/works
#    command: python src/main.py --runner=s8_cleanup
