

2025-06-04T15:18:15.376284Z      4402 Connect   root@192.168.144.3 on  using TCP/IP
2025-06-04T15:18:15.376429Z      4402 Query     SET NAMES utf8mb4
2025-06-04T15:18:15.376640Z      4402 Query     SET NAMES 'utf8mb4' COLLATE 'utf8mb4_unicode_520_ci'
2025-06-04T15:18:15.376724Z      4402 Query     SELECT @@SESSION.sql_mode
                                                    2025-06-04T15:18:15.376887Z      4402 Query     SET SESSION sql_mode='NO_ENGINE_SUBSTITUTION'
2025-06-04T15:18:15.377025Z      4402 Init DB   wordpress
2025-06-04T15:18:15.377527Z      4402 Query     SELECT option_name, option_value FROM wp_options WHERE autoload IN ( 'yes', 'on', 'auto-on', 'auto' )
    2025-06-04T15:18:15.381498Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'uninstall_plugins' LIMIT 1
2025-06-04T15:18:15.382081Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'harikrutfiwu_options' LIMIT 1
2025-06-04T15:18:15.384386Z      4402 Query     SHOW TABLES LIKE 'wp\\_snippets'
2025-06-04T15:18:15.385110Z      4402 Query     SELECT id, code, scope, active
                                                FROM wp_snippets
                                                WHERE scope IN ('global','single-use','front-end') AND active=1
                                                ORDER BY priority, id
                                                                                                                                                                                                                                                                                                                   2025-06-04T15:18:15.385845Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'WPLANG' LIMIT 1
2025-06-04T15:18:15.388338Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'generate_settings' LIMIT 1
2025-06-04T15:18:15.388649Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'using_application_passwords' LIMIT 1
2025-06-04T15:18:15.392541Z      4402 Query     SELECT option_name, option_value FROM wp_options WHERE option_name IN ('_site_transient_wp_theme_files_patterns-a6ce2d865f5ca1b739177d9b4e1178dc','_site_transient_timeout_wp_theme_files_patterns-a6ce2d865f5ca1b739177d9b4e1178dc')
    2025-06-04T15:18:15.392769Z      4402 Query     SELECT autoload FROM wp_options WHERE option_name = '_site_transient_wp_theme_files_patterns-a6ce2d865f5ca1b739177d9b4e1178dc'
    2025-06-04T15:18:15.392958Z      4402 Query     SHOW FULL COLUMNS FROM `wp_options`
                                                        2025-06-04T15:18:15.393658Z      4402 Query     DELETE FROM `wp_options` WHERE `option_name` = '_site_transient_wp_theme_files_patterns-a6ce2d865f5ca1b739177d9b4e1178dc'
    2025-06-04T15:18:15.394244Z      4402 Query     SELECT autoload FROM wp_options WHERE option_name = '_site_transient_timeout_wp_theme_files_patterns-a6ce2d865f5ca1b739177d9b4e1178dc'
    2025-06-04T15:18:15.394427Z      4402 Query     DELETE FROM `wp_options` WHERE `option_name` = '_site_transient_timeout_wp_theme_files_patterns-a6ce2d865f5ca1b739177d9b4e1178dc'
    2025-06-04T15:18:15.394817Z      4402 Query     INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('_site_transient_timeout_wp_theme_files_patterns-a6ce2d865f5ca1b739177d9b4e1178dc', '1749052095', 'off') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`)
    2025-06-04T15:18:15.395148Z      4402 Query     INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('_site_transient_wp_theme_files_patterns-a6ce2d865f5ca1b739177d9b4e1178dc', 'a:2:{s:7:\"version\";s:5:\"3.5.1\";s:8:\"patterns\";a:0:{}}', 'off') ON DUPLICATE KEY UPDATE `option_name` = VALUES(`option_name`), `option_value` = VALUES(`option_value`), `autoload` = VALUES(`autoload`)
    2025-06-04T15:18:15.395803Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'bunnycdn_offloader_enabled' LIMIT 1
2025-06-04T15:18:15.395968Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'bunnycdn_offloader_storage_zone' LIMIT 1
2025-06-04T15:18:15.396169Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'bunnycdn_offloader_storage_zoneid' LIMIT 1
2025-06-04T15:18:15.396357Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'bunnycdn_offloader_storage_password' LIMIT 1
2025-06-04T15:18:15.396533Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'bunnycdn_offloader_sync_existing' LIMIT 1
2025-06-04T15:18:15.396721Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'bunnycdn_offloader_sync_token_hash' LIMIT 1
2025-06-04T15:18:15.396883Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'bunnycdn_offloader_excluded' LIMIT 1
2025-06-04T15:18:15.397175Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'bunnycdn_cdn_disable_admin' LIMIT 1
2025-06-04T15:18:15.397436Z      4402 Query     SELECT option_value FROM wp_options WHERE option_name = 'bunnycdn_fonts_enabled' LIMIT 1
2025-06-04T15:18:15.403435Z      4402 Query     SELECT * FROM wp_users WHERE user_login = 'gary' LIMIT 1
2025-06-04T15:18:15.403788Z      4402 Query     SELECT user_id, meta_key, meta_value FROM wp_usermeta WHERE user_id IN (1) ORDER BY umeta_id ASC
    2025-06-04T15:18:15.404534Z      4402 Query     SHOW FULL COLUMNS FROM `wp_terms`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      2025-06-04T15:18:15.405249Z      4402 Query     SELECT  t.term_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      FROM wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      WHERE tt.taxonomy IN ('post_tag') AND t.name IN ('ডেটা স্ট্রাকচারে স্ট্যাক অপারেশন')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ORDER BY t.name ASC
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          2025-06-04T15:18:15.405682Z      4402 Query     SELECT t.term_id FROM wp_terms AS t INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id INNER JOIN wp_term_relationships AS pll_tr ON pll_tr.object_id = t.term_id WHERE tt.taxonomy = 'post_tag' AND t.name = 'ডেটা স্ট্রাকচারে স্ট্যাক অপারেশন' AND pll_tr.term_taxonomy_id = 280
    2025-06-04T15:18:15.406146Z      4402 Query     SELECT  t.term_id
                                                    FROM wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id
                                                    WHERE tt.taxonomy IN ('post_tag') AND t.slug IN ('%e0%a6%a1%e0%a7%87%e0%a6%9f%e0%a6%be-%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%b0%e0%a6%be%e0%a6%95%e0%a6%9a%e0%a6%be%e0%a6%b0%e0%a7%87-%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%af%e0%a6%be%e0%a6%95')
                                                    ORDER BY t.term_id ASC
                                                        LIMIT 1
2025-06-04T15:18:15.406368Z      4402 Query     SELECT t.*, tt.* FROM wp_terms AS t INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id WHERE t.term_id IN (3219)
    2025-06-04T15:18:15.406655Z      4402 Query     SELECT t.term_id FROM wp_terms AS t INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id INNER JOIN wp_term_relationships AS pll_tr ON pll_tr.object_id = t.term_id WHERE t.slug = '%e0%a6%a1%e0%a7%87%e0%a6%9f%e0%a6%be-%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%b0%e0%a6%be%e0%a6%95%e0%a6%9a%e0%a6%be%e0%a6%b0%e0%a7%87-%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%af%e0%a6%be%e0%a6%95' AND pll_tr.term_taxonomy_id = 280 AND tt.taxonomy = 'post_tag'
    2025-06-04T15:18:15.407029Z      4402 Query     SELECT  t.term_id
                                                    FROM wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id
                                                    WHERE tt.taxonomy IN ('post_tag') AND t.name IN ('ডেটা স্ট্রাকচারে স্ট্যাক অপারেশন') AND tt.parent = '0'
                                                    ORDER BY t.name ASC
                                                        2025-06-04T15:18:15.407474Z      4402 Query     SELECT  t.term_id
                                                                                                        FROM wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id
                                                                                                        WHERE t.slug IN ('%e0%a6%a1%e0%a7%87%e0%a6%9f%e0%a6%be-%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%b0%e0%a6%be%e0%a6%95%e0%a6%9a%e0%a6%be%e0%a6%b0%e0%a7%87-%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%af%e0%a6%be%e0%a6%95')
                                                                                                        ORDER BY t.term_id ASC
                                                                                                            LIMIT 1
2025-06-04T15:18:15.407843Z      4402 Query     SELECT  t.term_id
                                                FROM wp_terms AS t  INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id
                                                WHERE tt.taxonomy IN ('post_tag') AND t.slug IN ('%e0%a6%a1%e0%a7%87%e0%a6%9f%e0%a6%be-%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%b0%e0%a6%be%e0%a6%95%e0%a6%9a%e0%a6%be%e0%a6%b0%e0%a7%87-%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%af%e0%a6%be%e0%a6%95')

                                                                                                                                                                LIMIT 1
2025-06-04T15:18:15.408169Z      4402 Query     SELECT slug FROM wp_terms WHERE slug = '%e0%a6%a1%e0%a7%87%e0%a6%9f%e0%a6%be-%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%b0%e0%a6%be%e0%a6%95%e0%a6%9a%e0%a6%be%e0%a6%b0%e0%a7%87-%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%af%e0%a6%be%e0%a6%95'
    2025-06-04T15:18:15.408383Z      4402 Query     SELECT slug FROM wp_terms WHERE slug = '%e0%a6%a1%e0%a7%87%e0%a6%9f%e0%a6%be-%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%b0%e0%a6%be%e0%a6%95%e0%a6%9a%e0%a6%be%e0%a6%b0%e0%a7%87-%e0%a6%b8%e0%a7%8d%e0%a6%9f%e0%a7%8d%e0%a6%af%e0%a6%be%e0%a6%95-2'
    2025-06-04T15:18:15.409318Z      4402 Quit