name = "luckvideos-player"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[rules]]
type = "Text"
globs = ["**/*.css"]
fallthrough = true

[dev]
port = 8000

[[d1_databases]]
binding = "DB"
database_name = "luckvideos-db"
database_id = "local"
