name = "luckvideos-player"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[rules]]
type = "Text"
globs = ["**/*.css"]
fallthrough = true

[dev]
port = 8000

[[d1_databases]]
binding = "DB"
database_name = "luckvideos-db"
database_id = "local"

[triggers]
crons = ["*/10 * * * *"]

[vars]
VIDEO_FETCH_API_URL = ""
VIDEO_FETCH_API_KEY = ""
SLUG_OFFSET_VALUE = "0"
